server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # 1. Ruta para el Microservicio de Reportes de Incendios
        - id: ms-deteccion-y-reporte
          uri: https://ms-deteccion-y-reporte.onrender.com
          predicates:
            - Path=/api/reportes/**

        # 2. NUEVA RUTA: Redirige las peticiones de usuarios al mismo microservicio
        - id: ms-usuarios-routing
          uri: https://ms-deteccion-y-reporte.onrender.com
          predicates:
            - Path=/api/v1/usuarios/**