server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*" 
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      # ------------------------------------------
      routes:
        # Reportes de Incendios
        - id: ms-deteccion-y-reporte
          uri: https://ms-deteccion-y-reporte.onrender.com
          predicates:
            - Path=/api/reportes/**

        # peticiones de usuarios al mismo microservicio
        - id: ms-usuarios-routing
          uri: https://ms-deteccion-y-reporte.onrender.com
          predicates:
            - Path=/api/v1/usuarios/**

        # --- ALERTAS  ---
        - id: ms-alertas
          uri: http://localhost:10000   # El puerto donde corre tu Spring Boot de Reportes
          predicates:
            - Path=/api/alertas/**